PACKAGE_NAME="lvda"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="lvda"
BUILT_MODULE_LOCATION[0]="module"
DEST_MODULE_LOCATION[0]="/extra"

MAKE[0]="make -C module KDIR=${kernel_source_dir}"

AUTOINSTALL="yes"
